version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STAGE=bot
    volumes:
      - ./data:/app/data
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STAGE=web
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: always
