version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STAGE=bot
    volumes:
      - ./data:/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STAGE=web
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
